
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/mps/Desktop/Projects/New folder/YogaPoseCorrector-master/venv/Lib/site-packages/cmake/data/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...
